version: 0.2

env:
  variables:
    SOLUTION: .\muratmola.com_sln.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.5.2

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\NuGet.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Windows\Microsoft.NET\Framework64\v4.0.30319"'
artifacts:
  files:
    - .\muratmola.com\bin\Debug\*